# Generated by Django 4.2.4 on 2023-08-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_event_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=200)),
                ('attending', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
            ],
        ),
    ]
