# Generated by Django 4.2.4 on 2023-08-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sport',
            field=models.CharField(choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Baseball', 'Baseball')], max_length=100),
        ),
    ]
