# Generated by Django 4.2.4 on 2023-08-16 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_alter_event_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Party Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sport',
            field=models.CharField(choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Baseball', 'Baseball')], default='Football', max_length=100),
        ),
    ]
