# Generated by Django 4.2.4 on 2023-08-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_comment_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='2023-08-28', verbose_name='Party Date'),
        ),
    ]
