# Generated by Django 4.2.4 on 2023-08-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='map_url',
            field=models.URLField(blank=True),
        ),
    ]
