# Generated by Django 4.2.4 on 2023-08-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_event_attendees'),
        ('main_app', '0007_event_attendees_alter_event_sport'),
    ]

    operations = [
    ]
